import type { Metadata } from "next";

const favicon = "/static/images/invoicify-logo.png";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: favicon,
    shortcut: favicon,
    apple: favicon,
  },
};

import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

// Import styles
import "@/styles/styles.scss";

// Import templates
import Header from "@/templates/authenticated/header";
import Footer from "@/templates/authenticated/footer";
import Sidebar from "@/templates/authenticated/sidebar";

import { SessionProviderWrapper } from "@/wrappers/SessionProviderWrapper";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProviderWrapper>

          <div className="sidebar-holder">
            <Sidebar />
          </div>

          {/* This is the main content area */}
          <div className="website">

            <div className="header-holder">
              {/* This is the header component */}
              <Header />
            </div>
            <div className="website-content">
              {children}
            </div>

            <div className="footer-holder">
              {/* This is the footer component */}
              <Footer />
            </div>
          </div>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
